### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by bartrikers** [appronto/GoogleAutocomplete#3]
Hi,

Great widget! However, the validation part seems to be broken. When adding validation feedback, I can see the _addValidation function is called

![afbeelding](https://user-images.githubusercontent.com/23105910/43759980-217f208a-9a21-11e8-8a3a-c91bf1302ccd.png)

but html.set cannot be executed, because html is undefined...

![afbeelding](https://user-images.githubusercontent.com/23105910/43759994-28f8472e-9a21-11e8-9f13-54307c547910.png)

Kind regards,
Bart Rikers

**Comment by bartrikers** [comment]
problem is that the dojo/html constructor is not included. This fixes the issue:

![afbeelding](https://user-images.githubusercontent.com/23105910/43760584-d16b22f4-9a22-11e8-93fc-7e7a548271b4.png)

**Comment by joelvdgraaf** [comment]
Thanks, I fixed it with the new 1.1.0 version!
